### ISSUE TITLE
HOW TO ...

### ISSUE THREAD

**Issue by T3MPN4ME** [lishu/Jock.Net.TcpJson#2]
Hi @lishu, Thanks for the useful library :D
But i don't know how to send/receive the **TcpJsonPackage**

### Client:
`
 client.SendPackage(new TcpJsonPackage() { Type = TcpJsonPackageType.Command, Data = "You're fired!"});
`

### Server_Connected Method at Server:
`
 e.ServerClient.OnReceive<TcpJsonPackage>((package, client) => {
                    Console.WriteLine($"The boss says: {package.Data}");
                });
`

But nothing receiving or exception, What is wrong?

**Comment by lishu** [comment]
TcpJsonPackage is only used for internal data packaging formats, and it should not be used directly.

You should use other public `Send` and `OnRecive` methods for sending and receiving operations.
For example, use `SendCommand` to send a string command and use `OnReceiveCommand` to receive it.
The `OnReceive<T>` method will receive `SendObject<T>` data if the have same T class.
**Like you see, `Send` and `OnRecive`  are One by one correspondence.**

**Comment by T3MPN4ME** [comment]
Thanks for replay
it's true, I was wrong :man_facepalming:
The idea of ​​**SendPackage** for send **managed packet** was wrong
I must send my class as an object

**Like serialize:**
`
    client.SendObject(new NetPacket() {Type = DataType.Image, Data = imgBytes });
`

**And deserialize:**
`
e.ServerClient.OnReceive<NetPacket>((P, client) => {
                   Console.WriteLine("Recived {0} with size: {1}", (P.Type == DataType.Image) ? "Image" : "Text", P.Data.Length);
    })
`

And now work like a charm ! :nerd_face:
Thanks for your guidance.

**Comment by lishu** [comment]
I'm glad to be able to help you. (With my bad English.)
