### ISSUE TITLE
OnReceiveRequest in the TcpJsonClient

### ISSUE THREAD

**Issue by M4D3V2000** [lishu/Jock.Net.TcpJson#4]
Hi @lishu, Why nothing request receiving from server?

**Client:**
```
Client.OnReceiveRequest<string, string>("ID", (request, c) => Guid.NewGuid().ToString());
```
**Server:**
```
private static void Server_Connected(object sender, ConnectedEventArgs e)
{
     Console.WriteLine("New Client Connected");
     var ID = e.ServerClient.SendRequest("ID", string.Empty, 10000); //10 seconds for localhost? :D
     Console.WriteLine("Client ID: {0}", ID);
}
```
>Exception thrown: System.TimeoutException: 'Response is Timeout!'

I don't know what the problem ...

**Comment by lishu** [comment]
If only see your pasted code, just about right.
Request & Response has sample code in Test Project use `#region New ... in Release 1.0.1` block it, and you can see it work.
Just Make sure your Client call the Start method to run.
Timeout for the complete request and response process.

**Comment by M4D3V2000** [comment]
No, I realized the problem today
Conversely, `SendRequest` only works in the **client** and the **server** can `OnReceiveRequest`
It would be nice if library was not like HTTP :unamused:

I can't decide about library but `SendRequest` more used than `SendCommand` (work in server) :(

**Comment by M4D3V2000** [comment]
Run this [**code**](https://github.com/lishu/Jock.Net.TcpJson/files/2568289/Program.txt)
I hope you see problems ...

**Comment by lishu** [comment]
In Connected event handler invoke `SendRequest` will not working because the `ServerClient` core thread start after this event. This means that network packet processing does not have a chance to occur.

I has changed core thread start before this event, just wait upload.

**Comment by M4D3V2000** [comment]
Thanks @lishu ! Problem solved.
