### ISSUE TITLE
Client OnStoped, How to start again?

### ISSUE THREAD

**Issue by M4D3V2000** [lishu/Jock.Net.TcpJson#5]
all methods, functions, properties tested, and I think this is the last issue about problems ...

```javascript
Client.OnStoped(C => {
       Console.WriteLine("Client OnStoped, Restart after 2s");
       Thread.Sleep(2000);
       C.Start(); //Throw Exception
});
```
`e.ServerClient.Stop();`

**UnhandledExceptionEvent in Client:**
> Cannot access a disposed object.
> Object name: 'System.Net.Sockets.Socket'

What's the solution? :man_facepalming:
If there is new **update**:
- Please in TcpJsonClient, remove the "remoteEP" parameter from `Start` method
-  ~~Send and~~ Receive request without blocking ui (On Response CallBack)
- Send and receive large data (~~Already throw **Newtonsoft.Json.JsonSerialization** and **System.ObjectDisposed** exception on receive~~)

No i was wrong! **Newtonsoft.Json.JsonSerialization** meaning when **send** :man_facepalming:

**i changed this:** 
`OnReceiveRequest<string, Image>("Image", (request, C) => img); //Newtonsoft.Json.JsonSerialization Exception`
**to:**
`OnReceiveRequest<string, string>("Image", (request, C) => imgStr); // i convert the image to string (base64)` 

For send an **image** !
Now i transfer image with size 239 KB and then received it :D

**Comment by lishu** [comment]
If you want restart in onstoped callback, 
You need to use the Start method with the same specific parameters as before.
Is means `Start() -> Start()` and `Start(EP) -> Start(EP)` will work.
[Client Connect](https://github.com/lishu/Jock.Net.TcpJson/wiki/Client-Connect) has clearly stated that methods with and without parameters have different ways of handling. No like no parameters method is short way parameters method, So can not just remove some parameters.

**Comment by lishu** [comment]
As you known, This lib is base Json and Lightweight app
I think it would be a better idea to build a WEBAPI service to handle large data directly.

If you still want to use this framework to work with big data, I may not be able to ensure support.

The most appropriate usage is that each package is processed no more than 2k byte of data.

**Comment by lishu** [comment]
I will try write a full chat room as a demo, But it can only be written slowly in my spare time.

**Comment by AHM4DR3Z4** [comment]
Maybe it's hard work but certainly always there is a way
You're doing well And until now, you have solved all the problems :))
It's true that my goal is to create a messenger, but in addition to chatting, there must be features for sending and receiving files.
And also I want the Server to be a executable code! 

Thanks for your following up! :grin:

**Comment by M4D3V2000** [comment]
Where is version [1.0.5](https://www.nuget.org/packages/Jock.Net.TcpJson/)?
I'm still waiting for fix this bug(s) in new update :(

[Edit]
`OnStoped` bug fixes, but what do you think about my suggestion? ([OnResponse CallBack](https://pastebin.com/uQsekmHL))

**Comment by lishu** [comment]
Try Async version of Request method `SendRequestAsync`, This is a Standard asynchronous mode，but can not use in framework 3.5, See more at [Asynchronous programing](https://docs.microsoft.com/en-us/dotnet/csharp/async).

**Comment by M4D3V2000** [comment]
I know but as you yourself said: "_you can not use the 3.5 framework_"

**e.g:** Something like [WebClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient)
```javascript
var client = new WebClient();
client.DownloadStringCompleted += (sender, e) => /* what the library needs */
{
   doSomeThing(e.Result);
};

client.DownloadStringAsync(uri); //this will keep GUI responsive
```
and if there was no response or `timeout`, the result would be null !
with this feature, both server and client will be optimized (in terms of management).

**Comment by lishu** [comment]
I'm sorry, this library development goal is clearly based on. Net Standard 2.0.

This means that support for version 3.5 is limited because what I want is lightweight and popular, using an intuitive communications library. If version 3.5 is supported, a large number of begin/complete methods will appear, and for me, such things are as completely unacceptable as poop when they already support tasks asynchronously.
